name: GitHub Actions Test 2
run-name: ${{ github.actor }} in Action 🚀
on:
    push:
        branches:
            - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
    
      - name: Build and tag docker image
        run : |
          docker build -t ${{secrets.USERNAME}}/action-project1:v1 -f Dockerfile .
          
      - name: Push to Dockerhub 
        run : docker login -u ${{secrets.USERNAME}} -p ${{secrets.USERNAME}} && docker push ${{secrets.USERNAME}}/action-project1:v1

         